# This file is included by the main Makefile, and contains the settings

TAP_DANCE_ENABLE=no # Enable tap dance

EXTRAKEY_ENABLE=yes
OLED_DRIVER_ENABLE=no
BOOTMAGIC_ENABLE=no
MOUSEKEY_ENABLE=no
SWAP_HANDS_ENABLE=no

CONSOLE_ENABLE=no
COMMAND_ENABLE=no

# SAVE SOME BYTES
GRAVE_ESC_ENABLE=no

BLUETOOTH_ENABLE=no
DYNAMIC_MACRO_ENABLE = no
KEY_LOCK_ENABLE = no
VELOCIKEY_ENABLE = no
STENO_ENABLE = no
TERMINAL_ENABLE = no
AUTO_SHIFT_ENABLE = no
POINTING_DEVICE_ENABLE = no
RAW_ENABLE = no
SEQUENCER_ENABLE = no
WPM_ENABLE = no
OLED_ENABLE = no
AUTO_SHIFT_MODIFIERS = no
LTO_ENABLE = yes
VIA_ENABLE = no
MIDI_ENABLE=no
AUDIO_ENABLE=no
